version: "3"

services:
  db:
    container_name: subsquid_db
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: squid
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    shm_size: 1gb
  # processor:
  #   image: my-squid
  #   environment:
  #     - DB_NAME=squid
  #     - DB_PORT=5432
  #     - DB_HOST=db
  #     - DB_PASS=squid
  #   ports:
  #     # prometheus metrics exposed at port 3000
  #     - "3000:3000"
  #   command: ["sqd", "process:prod"]
  #   depends_on:
  #     - db
