apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: 921618787109.dkr.ecr.eu-central-1.amazonaws.com/squid-azero-processor:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "subsquid-db-service.default"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "squid"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "squid"
      imagePullSecrets:
        - name: regcred
# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: processor-service
# spec:
#   selector:
#     app: processor
#   type: ClusterIP
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
