apiVersion: v1
kind: Service
metadata:
  name: querynode-service
spec:
  selector:
    app: querynode
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4350
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: querynode-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: querynode
  template:
    metadata:
      labels:
        app: querynode
    spec:
      containers:
        - name: querynode
          image: 921618787109.dkr.ecr.eu-central-1.amazonaws.com/squid-azero-querynode
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "subsquid-db-service.default"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "squid"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "squid"
      imagePullSecrets:
        - name: regcred
