apiVersion: v1
kind: Service
metadata:
  name: subsquid-db-service
spec:
  selector:
    app: subsquid-db
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subsquid-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subsquid-db
  template:
    metadata:
      labels:
        app: subsquid-db
    spec:
      containers:
        - name: subsquid-db
          image: postgres:14
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: "squid"
            - name: POSTGRES_PASSWORD
              value: "squid"
