export * as balances from './balances/calls'
export * as evm from './evm/calls'
export * as ethereum from './ethereum/calls'
export * as ethCall from './eth-call/calls'
export * as dappsStaking from './dapps-staking/calls'
export * as baseFee from './base-fee/calls'
export * as contracts from './contracts/calls'
export * as dappStaking from './dapp-staking/calls'
