name: Test build on PR and deploy to ECR on merge/push

on:
  push:
    branches: ["branch"]
  pull_request:
    branches: ["branch"]
  workflow_dispatch:

jobs:
  deploy:
    uses: tokenguardio/substrate-squids/.github/workflows/reusable-ecr-deploy.yaml@reusable-workflows
    secrets: inherit
