name: Test build on PR and deploy to ECR on merge/push

on:
  push:
    branches: ["moonbeam-mainnet-wglmr-evm"]
  pull_request:
    branches: ["moonbeam-mainnet-wglmr-evm"]
  workflow_dispatch:

jobs:
  compliance:
    uses: tokenguardio/substrate-squids/.github/workflows/reusable-ecr-deploy.yaml@reusable-workflows
    secrets: inherit
  compliance-new-infra:
    uses: tokenguardio/substrate-squids/.github/workflows/reusable-ecr-deploy-prod.yaml@reusable-workflows
    secrets: inherit
