name: Test build on PR and deploy to ECR on merge/push

on:
  push:
    branches: ["ethereum-mainnet-evm-parquet-s2-a-final"]
  pull_request:
    branches: ["ethereum-mainnet-evm-parquet-s2-a-final"]
  workflow_dispatch:

jobs:
  compliance:
    uses: tokenguardio/substrate-squids/.github/workflows/reusable-ecr-deploy.yaml@reusable-workflows
    secrets: inherit
  compliance-new-infra:
    uses: tokenguardio/substrate-squids/.github/workflows/reusable-ecr-deploy-prod.yaml@reusable-workflows
    secrets: inherit
