name: Deploy to ECR

on:
  push:
    branches: ["azero-testnet-reusable-test"]
  pull_request:
    branches: ["azero-testnet-reusable-test"]
  workflow_dispatch:

jobs:
  compliance:
    uses: tokenguardio/substrate-squids/.github/workflows/reusable-ecr-deploy.yml@reusable-workflows
