name: Deploy to ECR on Reef Mainnet

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The name of the branch to deploy"
        required: true
        default: "reef-mainnet"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ECR
        uses: ./.github/workflows/reusable-deploy.yaml
