name: Deploy to ECR on Reef Mainnet

on:
  push:
    branches: ["reef-mainnet"]
  pull_request:
    branches: ["reef-mainnet"]
  workflow_dispatch:
    inputs:
      branch:
        description: "The name of the branch to deploy"
        required: true
        default: "reef-mainnet"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to ECR
        uses: ./.github/workflows/reusable-deploy.yaml
